# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# Manually Changed, DO NOT OVERWRITE IF CHANGING VIA Qt Designer
from Pendulum import Pendulum
import sim
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
from matplotlib.animation import TimedAnimation
from matplotlib.lines import Line2D
mpl.use('Qt5Agg')


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 524)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.frame_3)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.lengthSpinBox = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.lengthSpinBox.setStyleSheet("font: 9pt \"Arial\";")
        self.lengthSpinBox.setDecimals(4)
        self.lengthSpinBox.setMaximum(1000.0)
        self.lengthSpinBox.setProperty("value", 1.0)
        self.lengthSpinBox.setObjectName("lengthSpinBox")
        self.gridLayout.addWidget(self.lengthSpinBox, 1, 1, 1, 1)
        self.intervalSpinBox = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.intervalSpinBox.setStyleSheet("font: 9pt \"Arial\";")
        self.intervalSpinBox.setDecimals(4)
        self.intervalSpinBox.setProperty("value", 0.0125)
        self.intervalSpinBox.setObjectName("intervalSpinBox")
        self.gridLayout.addWidget(self.intervalSpinBox, 6, 1, 1, 1)
        self.gSpinBox = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.gSpinBox.setStyleSheet("font: 9pt \"Arial\";")
        self.gSpinBox.setDecimals(4)
        self.gSpinBox.setMinimum(-1000.0)
        self.gSpinBox.setMaximum(1000.0)
        self.gSpinBox.setProperty("value", -9.81)
        self.gSpinBox.setObjectName("gSpinBox")
        self.gridLayout.addWidget(self.gSpinBox, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setStyleSheet("font: 9pt \"Arial\";")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setStyleSheet("font: 9pt \"Arial\";")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setStyleSheet("font: 75 9pt \"Arial\";")
        self.label_8.setWordWrap(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.pivotCoorLineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.pivotCoorLineEdit.setStyleSheet("font: 9pt \"Arial\";")
        self.pivotCoorLineEdit.setObjectName("pivotCoorLineEdit")
        self.gridLayout.addWidget(self.pivotCoorLineEdit, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setStyleSheet("font: 9pt \"Arial\";")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.angleSpinBox = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.angleSpinBox.setStyleSheet("font: 9pt \"Arial\";")
        self.angleSpinBox.setDecimals(4)
        self.angleSpinBox.setMinimum(-1.0)
        self.angleSpinBox.setMaximum(1.0)
        self.angleSpinBox.setProperty("value", -0.5)
        self.angleSpinBox.setObjectName("angleSpinBox")
        self.gridLayout.addWidget(self.angleSpinBox, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setStyleSheet("font: 9pt \"Arial\";")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setStyleSheet("font: 9pt \"Arial\";")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setStyleSheet("font: 9pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.angularVelocitySpinBox = QtWidgets.QDoubleSpinBox(self.widget_2)
        self.angularVelocitySpinBox.setStyleSheet("font: 9pt \"Arial\";")
        self.angularVelocitySpinBox.setDecimals(4)
        self.angularVelocitySpinBox.setMinimum(-1000.0)
        self.angularVelocitySpinBox.setMaximum(1000.0)
        self.angularVelocitySpinBox.setProperty("value", 0.0)
        self.angularVelocitySpinBox.setObjectName("angularVelocitySpinBox")
        self.gridLayout.addWidget(self.angularVelocitySpinBox, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.frame_3)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.applyButton = QtWidgets.QPushButton(self.widget_4)
        self.applyButton.setEnabled(True)
        self.applyButton.setStyleSheet("font: 9pt \"Arial\";")
        self.applyButton.setCheckable(False)
        self.applyButton.setAutoDefault(False)
        self.applyButton.setDefault(True)
        self.applyButton.setObjectName("applyButton")
        self.verticalLayout_3.addWidget(self.applyButton)
        self.changesLabel = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.changesLabel.setFont(font)
        self.changesLabel.setStyleSheet("font: 9pt \"Arial\";\n"
"color: rgb(255, 0, 0);")
        self.changesLabel.setText("")
        self.changesLabel.setWordWrap(True)
        self.changesLabel.setObjectName("changesLabel")
        self.verticalLayout_3.addWidget(self.changesLabel)
        self.label_7 = QtWidgets.QLabel(self.widget_4)
        self.label_7.setStyleSheet("font: 9pt \"Arial\";")
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_4)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setStyleSheet("font: 9pt \"Arial\";")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.saveButton = QtWidgets.QPushButton(self.widget_4)
        self.saveButton.setEnabled(False)
        self.saveButton.setStyleSheet("font: 9pt \"Arial\";")
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_3.addWidget(self.saveButton)
        self.saveLabel = QtWidgets.QLabel(self.widget_4)
        self.saveLabel.setStyleSheet("font: 9pt \"Arial\";\n"
"color: rgb(255, 0, 0);")
        self.saveLabel.setText("")
        self.saveLabel.setWordWrap(True)
        self.saveLabel.setObjectName("saveLabel")
        self.verticalLayout_3.addWidget(self.saveLabel)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(500, 500))
        self.frame.setMaximumSize(QtCore.QSize(500, 500))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.vLayout = QtWidgets.QVBoxLayout()
        self.vLayout.setObjectName("vLayout")
        self.gridLayout_2.addLayout(self.vLayout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        # Manually Changed, DO NOT OVERWRITE IF CHANGING VIA Qt Designer
        self.canvas = CustomCanvas()
        self.vLayout.addWidget(self.canvas)

        # Manually Changed, DO NOT OVERWRITE IF CHANGING VIA Qt Designer
        self.lengthSpinBox.valueChanged['double'].connect(
            lambda: self.toggleButton(self.applyButton, True))
        self.gSpinBox.valueChanged['double'].connect(
            lambda: self.toggleButton(self.applyButton, True))
        self.angleSpinBox.valueChanged['double'].connect(
            lambda: self.toggleButton(self.applyButton, True))
        self.angularVelocitySpinBox.valueChanged['double'].connect(
            lambda: self.toggleButton(self.applyButton, True))
        self.intervalSpinBox.valueChanged['double'].connect(
            lambda: self.toggleButton(self.applyButton, True))
        self.pivotCoorLineEdit.textChanged['QString'].connect(
            lambda: self.toggleButton(self.applyButton, True))
        self.applyButton.clicked.connect(self.simulate)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Pendulum Simulator"))
        self.label_4.setText(_translate("MainWindow", "Pivot Coordinates (x,y):"))
        self.label_3.setText(_translate("MainWindow", "Initial Angular Velocity:"))
        self.label_8.setText(_translate("MainWindow", "Type in paramters, they\'re in SI units:"))
        self.pivotCoorLineEdit.setText(_translate("MainWindow", "0,0"))
        self.label_5.setText(_translate("MainWindow", "Gravitational Accleration:"))
        self.label_6.setText(_translate("MainWindow", "Time Interval:"))
        self.label.setText(_translate("MainWindow", "Pendulum Length:"))
        self.label_2.setText(_translate("MainWindow", "Initial Angle (in terms of pi):"))
        self.applyButton.setText(_translate("MainWindow", "Simulate"))
        self.label_7.setText(_translate("MainWindow", "To save, type in full file path, including .mp4:"))
        self.saveButton.setText(_translate("MainWindow", "Save"))

    # Manually Changed, DO NOT OVERWRITE IF CHANGING VIA Qt Designer
    def simulate(self):
        self.toggleButton(self.applyButton, False)

        try:
            length = self.lengthSpinBox.value()
            g = self.gSpinBox.value()
            angle = self.angleSpinBox.value() * np.pi
            angularVelocity = self.angularVelocitySpinBox.value()
            pendCoor = self.pivotCoorLineEdit.text().split(",")
            interval = self.intervalSpinBox.value()

            ax = self.canvas.fig.add_subplot(111)
            ax.clear()

            pen = Pendulum(length, angle, angularVelocity, pendCoor)
            pos = sim.simulatePendulum(pen, interval, g)
            self.ani = sim.produceAnimation(pen, pos, interval * 1000,
                                            self.canvas.fig, ax)

            self.canvas.draw()
        except Exception as e:
            self.changesLabel.setText(str(e))

    # Manually Changed, DO NOT OVERWRITE IF CHANGING VIA Qt Designer
    @staticmethod
    def toggleButton(button, toggle):
        """
        Changes whether the button is enabled or disabled.

        Parameters
        ----------
        button : QPushButton
            The button to enable or disable,
        toggle : Bool
            Determines whether the button is enabled or disabled.
        """
        button.setEnabled(toggle)


# Manually Changed, DO NOT OVERWRITE IF CHANGING VIA Qt Designer
class CustomCanvas(FigureCanvasQTAgg):
    def __init__(self):
        self.fig = plt.figure(figsize = (5, 5), dpi = 140)

        FigureCanvasQTAgg.__init__(self, self.fig)
