name: Create Executable via Pyinstaller

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:  
      matrix:  
        python-version: ["3.13.7"]
        
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Add poetry path
        run: echo "C:\Users\runneradmin\.local\bin" >> $GITHUB_PATH
      - name: Install dependencies
        shell: bash
        run: poetry install --no-interaction --no-root
      - name: Create executable
        shell: bash
        run: poetry run pyinstaller pendulum.spec
      - name: Zip dist Folder
        run: Compress-Archive -Path ${{ github.workspace }}\dist\pendulum\* -Destination ${{ github.workspace }}\dist\pendulum${{ github.ref }}.zip
      - name: Add Folders to Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ github.workspace }}\dist\pendulum${{ github.ref }}.zip
