name: Run All Unit Tests via Pytest

on:
  push:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:  
      matrix:  
        python-version: ["3.12.7"]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip
          pip install numpy
          pip install pytest
          pip install ruff
      - name: Lint with Ruff  
        run: |  
          ruff check -v
        continue-on-error: true  
      - name: Test with pytest  
        run: |
          pytest  -v -s  
